name: Build Kivy APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Instalar dependencias
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip openjdk-17-jdk unzip
        pip install buildozer cython
        
    - name: Install AIDL
      run: sdkmanager "build-tools;36.0.0-rc5"

    - name: Compilar APK
      run: |
        buildozer android debug
        

    - name: Guardar APK como artefacto
      uses: actions/upload-artifact@v4
      with:
        name: MiAppKivy-APK
        path: bin/*.apk
