name: Build Kivy APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Instalar dependencias
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip openjdk-17-jdk unzip curl
        pip install buildozer cython

    - name: Configurar Android SDK
      run: |
        # Descargar e instalar el SDK de Android
        mkdir -p $HOME/android-sdk/cmdline-tools
        curl -o android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        unzip android-sdk.zip -d $HOME/android-sdk/cmdline-tools
        rm android-sdk.zip

        # Configurar variables de entorno
        export PATH=$PATH:$HOME/android-sdk/cmdline-tools/latest/bin
        export ANDROID_HOME=$HOME/android-sdk

    - name: Compilar APK
      run: |
        # Ejecución del buildozer para la compilación del APK
        # Usamos 'yes' para aceptar automáticamente las licencias cuando se soliciten
        yes | buildozer android debug

    - name: Guardar APK como artefacto
      uses: actions/upload-artifact@v4
      with:
        name: MiAppKivy-APK
        path: bin/*.apk
